
DROP TABLE IF EXISTS Customer;

CREATE TABLE Customer
	(id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)primary key ,
         name VARCHAR(64));

INSERT INTO Customer(id,name) 
   VALUES (1 , 'first customer');

select * from Customer;
